Module 1 Day 2 Microverse Project
Duncannjau/Hello-Microverse pull request #1
Opened 2022-06-30 19:42 UTC by Duncannjau

The purpose of this project is to master the importance of setting up Github workflows and actions. Setting the environment for ease of reviews, continuous integration & deployment and version control.

2022-06-30 20:23 UTC, cwaku requested changes
Hi @Duncannjau 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
There are a few issues 🐛  that you still need to work 🛠️  on to go to the next project ⏭️  but you are almost there! 🏃🏾 

## Highlights
- [x] Good commit messages 👍🏾 
- [x] Good task implementation 💯 
- [x] Correct use of Github flow 🥇 
- [x] Meaningful PR title and description 👍🏾 

## Required Changes ♻️
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips 🌟  that can improve your code quality 💯 and help you get a better job 💼.

I will guide 📔 you through fixing 🛠️ these bugs, follow my comments down below and make sure you don't miss any of them, in order to get your project approved ✅

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 20:23 UTC, cwaku commented on github/workflows/linters.yml
> +name: Linters
- [x] Your linter actions are not running because you named the folder wrongly. Kindly a `.` to the beginning of the folder's name to look like this `.github/workflows/linters.yml`

2022-06-30 20:23 UTC, cwaku commented on README.md
> +-Visual studio used as the compiler.
- [x] Good job for adding a custom `README.md` file to your project. To have it look more professional, kindly follow the [template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided and add the missing sections.

2022-06-30 23:27 UTC, Duncannjau commented on README.md
> +-Visual studio used as the compiler.
Thank you Cwaku for the encouragement and good review.I have renamed the folder correctly now

2022-07-01 07:23 UTC, sumairq approved these changes
Hi @Duncannjau , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 08:53 UTC, merged